lim:
  tcpPort: 8888
  webSocketPort: 18888
  bossThreadSize: 1
  workerThreadSize: 8
  heartBeatTime: 60 #心跳超时时间
  brokerId: 1000
  loginModel: 3
  url: http://localhost:6666/v1
  #  *                多端同步模式：1 只允许一端在线，手机/电脑/web 踢掉除了本client+imel的设备
  #  *                            2 允许手机/电脑的一台设备 + web在线 踢掉除了本client+imel的非web端设备
  #  *                            3 允许手机和电脑单设备 + web 同时在线 踢掉非本client+imel的同端设备
  #  *                            4 允许所有端多设备登录 不踢任何设备

  redis:
    mode: single  # 单机模式：single；哨兵模式：sentinel；集群模式：cluster
    database: 0
    password: 031119
    timeout: 5000 # 超时时间
    poolConnTimeout: 3000
    poolMinIdle: 8 # 最小空闲树
    poolSize: 10 # 连接池大小
    single: # Redis 单机配置
       address: 192.168.248.143:6379

  rabbitmq:
    host: 192.168.248.143
    port: 5672
    virtualHost: /ems
    userName: admin
    password: 123456
  zkConfig:
    zkAddr: 192.168.248.143
    zkConnectTimeOut: 5000
