lim:
  tcpPort: 8887
  webSocketPort: 18887
  bossThreadSize: 1
  workerThreadSize: 8
  heartBeatTime: 3000 #心跳超时时间 单位秒
  brokerId: 1001
  url: http://localhost:6666/v1

  redis:
    mode: single  # 单机模式：single；哨兵模式：sentinel；集群模式：cluster
    database: 0
    password: 031119
    timeout: 5000 # 超时时间
    poolConnTimeout: 3000
    poolMinIdle: 8 # 最小空闲树
    poolSize: 10 # 连接池大小
    single: # Redis 单机配置
       address: 192.168.248.143:6379

  rabbitmq:
    host: 192.168.248.143
    port: 5672
    virtualHost: /ems
    userName: admin
    password: 123456
  zkConfig:
    zkAddr: 192.168.248.143
    zkConnectTimeOut: 5000
